### PR TITLE
Enabling MultiGitRepos (and more)

### PR DESCRIPTION
**Pull request by Aryan-Barbarian**
This adds the GitRepo class which allows us to analyze the commit histories of multiple projects at once. #197. 

Also addresses the #199 bug where cached repos were not properly handled.

### CODE REVIEW

**Comment by Aryan-Barbarian** [comment]
Also, look at the MultiGitRepo ipython notebook for an example of how to generate such a repo.

**Comment by sbenthall** [comment]
There is so much here. Thanks for this super work, Aryan. If it's OK, I'd like for you to present these changes in our meeting today so that Ven and Jess can stay on top of the architectural changes.

**Comment by Aryan-Barbarian** [comment]
Totally. I'll be ready to explain everything. 

Also, with the past few commits I added a way to pull repos from an entire Github Organization (such as Code For America or Glass-Beads-Labs) and put them into a MultiGitRepo

It also fixes #206

**Comment by Aryan-Barbarian** [comment]
Also this addresses #146

**Pull request merged**
